version: "3.9"
services:
    python:
        build: .
        volumes:
            - ./volume:/home/volume
        networks:
            - main
        tty: true
    redis:
        image: "redis:6.2.6"
        ports:
            - "6379:6379"
        networks:
            - main
networks:
    main:
