version: "3.9"
services:
    python:
        build: .
        image: "psalire/url-whiteblacklist_python"
        volumes:
            - "./volume:/home/volume"
        ports:
            - "8080:8080"
        networks:
            - main
        depends_on:
            - redis
        tty: true
    redis:
        image: "redis:6.2.6"
        expose:
            - 8000
        networks:
            - main
networks:
    main:
